{
 "title": "Namespace View",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   }
  ]
 },
 "panels": [
  { "title": "Namespace: $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "HWM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aerospike_namespace_hwm_breached{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Unavailable Partitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(partitions{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Dead Partitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(partitions{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "% Memory Trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_memory_free_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Used %"
    },
    {
     "expr": "avg(aerospike_namespace_high_water_memory_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "High Water Mark"
    },
    {
     "expr": "avg(aerospike_namespace_stop_writes_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Stop Writes"
    }
   ]
  },
  {
   "title": "% Device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_device_available_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "% Device Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(100-aerospike_namespace_device_free_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Used % (Free)"
    },
    {
     "expr": "avg(100-aerospike_namespace_device_available_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Used % (Available)"
    },
    {
     "expr": "avg(aerospike_namespace_high_water_disk_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "High Water Mark"
    },
    { "expr": "95", "legendFormat": "Stop Writes" }
   ]
  },
  {
   "title": "% Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/sum(aerospike_namespace_memory_size{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aerospike_namespace_device_total_bytes{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aerospike_namespace_device_total_bytes{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_device_available_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aerospike_namespace_memory_size{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aerospike_namespace_memory_size{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})*(avg(aerospike_namespace_memory_free_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})/100)"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_tombstones{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Tombstones"
    },
    {
     "expr": "sum(aerospike_namespace_evicted_objects{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Evicted objects"
    },
    {
     "expr": "sum(aerospike_namespace_prole_objects{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Replica objects"
    },
    {
     "expr": "sum(aerospike_namespace_master_objects{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Master objects"
    }
   ]
  },
  {
   "title": "Migrate Partitions Remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Outgoing"
    }
   ]
  }
 ]
}