{
 "title": "Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\"},cluster_name)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(aerospike_node_stats_uptime{job=\"aerospike\", cluster_name=~\"$cluster|$^\"},service)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "aerospike_node_info{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"}"
      }
     ]
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "Agent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$service|$^\"})"
    }
   ]
  },
  {
   "title": "Server Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ALERTS{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Client Conns.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "All Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "All Tombstones",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_memory_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_total_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_device_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Latency: Reads / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"read\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: Writes / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"write\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: UDF / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"udf\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Migrations (Partitions Remaining)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Incoming Partitions Remaining"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Outgoing Partitions Remaining"
    }
   ]
  },
  {
   "title": "Latency: Query / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"query\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: Proxies / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"proxy\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Client Connections"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Fabric Connections"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Heartbeat Connections"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Master"
    },
    {
     "expr": "aerospike_namespace_prole_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Prole"
    },
    {
     "expr": "aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Tombstones"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Agent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(up{job=\"aerospike\", cluster_name=~\"$cluster|$^\", service=~\"$service|$^\"})"
    }
   ]
  },
  {
   "title": "Server Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_stats_cluster_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Client Conns.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "All Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "All Tombstones",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_size{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Mem.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_memory_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_total_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(aerospike_namespace_device_free_pct{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Latency: Reads / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"read\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: Writes / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"write\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: UDF / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"udf\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Migrations (Partitions Remaining)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(aerospike_namespace_migrate_rx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Incoming Partitions Remaining"
    },
    {
     "expr": "sum(aerospike_namespace_migrate_tx_partitions_remaining{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node\"})",
     "legendFormat": "Outgoing Partitions Remaining"
    }
   ]
  },
  {
   "title": "Latency: Query / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"query\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Latency: Proxies / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"aerospike_latencies_.*\", op_type=\"proxy\",job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (quartile_sorted)",
     "legendFormat": "{{quartile_sorted}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Client Connections"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Fabric Connections"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "Heartbeat Connections"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Master"
    },
    {
     "expr": "aerospike_namespace_prole_objects{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Prole"
    },
    {
     "expr": "aerospike_namespace_tombstones{job=\"aerospike\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{ns}}/Tombstones"
    }
   ]
  }
 ]
}