name: Docker

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      docker_tag: 
         description: Docker Tag
         required: false
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      uses: step-security/setup-buildx-action@6997872a55d77391e51b87609556578131f44402 # v4.1.0

    - name: Docker login
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set env
      run: |
        echo "DOCKER_TAG=$(echo $GITHUB_REF_NAME | cut -c 2-)" >> $GITHUB_ENV

    # Commenting below targets as we are verifying the difference between snyk cli and snyk website results
    #
    # - name: Set up Snyk CLI
    #   uses: snyk/actions/setup@cdb760004ba9ea4d525f2e043745dfe85bb9077e
    #   with:
    #       snyk-version: v1.1297.3

    # - name: Authenticate Snyk
    #   run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # - name: Run Vulnerability Scan
    #   run: |
    #      make vulnerability-scan

    # - name: Run Container Vulnerability Scan
    #   run: |
    #      make vulnerability-scan-container

    - name: Build and push
      run: |
        if [  "${{ github.event.inputs.docker_tag }}" == "" ]; then
            echo "Creating Docker Images with given Docker Tag  with GITHUB_REF_NAME - ".${{ env.DOCKER_TAG }}
            make VERSION=${{ env.DOCKER_TAG }} release-docker-multi-arch
        else
            echo "Creating Docker Images with Input Docker Tag value ".${{ github.event.inputs.docker_tag }}
            make VERSION=${{  github.event.inputs.docker_tag }} release-docker-multi-arch
        fi        
            